AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: An AWS Lambda application that calls the Lambda API.
Resources:
  function:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://lambda-artifacts-054859628a91e838/44ea48e2fde523793c5f8715a513af63
      Handler: orderprocessingsystem.Handler
      Runtime: java8
      Description: Java function
      MemorySize: 512
      Timeout: 15
      Policies:
      - AWSLambdaBasicExecutionRole
      - AWSLambdaReadOnlyAccess
      - AWSXrayWriteOnlyAccess
      - AWSLambdaVPCAccessExecutionRole
      Tracing: Active
      Layers:
      - Ref: libs
  libs:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: orderprocessingsystem-lib
      Description: Dependencies for the Java S3 sample app.
      ContentUri: s3://lambda-artifacts-054859628a91e838/e38f3615500930d469d8cd639c717cf0
      CompatibleRuntimes:
      - java8
